-- User Creation & Grants --

CREATE USER foo WITH PASSWORD 'bar';

DROP DATABASE IF EXISTS bookmyshow;
CREATE DATABASE bookmyshow;

GRANT CREATE ON DATABASE bookmyshow TO foo;

GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA public TO foo;

GRANT ALL PRIVILEGES
ON ALL SEQUENCES IN SCHEMA public TO foo;

GRANT EXECUTE
ON ALL FUNCTIONS IN SCHEMA public TO foo;
