# Generated by Django 3.1.1 on 2020-09-21 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Guid')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Movie Category')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Movie Genre',
                'verbose_name_plural': 'Movie Genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Guid')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('genres', models.ManyToManyField(blank=True, to='movies.Genre', verbose_name='Genres')),
                ('languages', models.ManyToManyField(blank=True, to='languages.Language', verbose_name='Languages')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
